### ISSUE TITLE
fever: Unable to fetch more than 50 articles from Miniflux Fever API

### ISSUE THREAD

**Issue by vxid** [fasheng/elfeed-protocol#27] opened 2020-02-29 14:50 UTC
Hi and thank you again for implementing the Fever API compatibility for elfeed.

I use a self hosted instance of Miniflux on a personal VPS.
I recently noticed that my feeds were not updating anymore (no errors when syncing with elfeed).
By removing the filters from the main elfeed views, I noticed that I only had 50 old articles, all marked as read, in the database. Deleting these old articles from the miniflux database and re-syncing syncs the next 50 articles, whether they are read or unread.

The next logical step was to change the value of  `elfeed-protocol-fever-maxsize` to a higher value, but it does not seem to have any effect...

The log I attached below comes from a run with  `elfeed-protocol-fever-maxsize` set to a value of 100. It seems to me that elfeed-protocol fetches the right amount of entries (100), but that only 50 of the entries (the default) are parsed...

I also attached my full elfeed configuration below:

```emacs-lisp
(use-package elfeed
  :ensure t
:config
(setq elfeed-use-curl t))

(use-package elfeed-protocol
  :ensure t
  :config
  (setq elfeed-protocol-fever-maxsize 100)
  (setq elfeed-feeds
        (list (list "fever+https://MYURL"
                    :api-url "https://MYURL/fever/"
                    :use-authinfo t)))
  (elfeed-protocol-enable))
```

- OS version: `NixOS 20.03`
- emacs version: `26.3`
- elfeed version: `elfeed-20200209.1942`
- elfeed-protocol version: `elfeed-protocol-20200224.243`

```
[2020-02-29 15:38:12] [debug]: elfeed-protocol-fever: update feed list
[2020-02-29 15:38:12] [debug]: retrieve (https://MYURL/fever/?api&feeds)
[2020-02-29 15:38:13] [debug]: elfeed-protocol-fever: update entries with action update, arg 966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165
[2020-02-29 15:38:13] [debug]: elfeed-protocol-fever: get entries 966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165
[2020-02-29 15:38:13] [debug]: retrieve (https://MYURL)
[2020-02-29 15:38:13] [debug]: elfeed-protocol-fever: update, parsing entries, entry-mark: 965
[2020-02-29 15:38:13] [debug]: elfeed-protocol-fever: update, parsed 50 entries(30 unread, 0 starred, min-entry-id 794, max-entry-id 965) with 0.010306s, entry-mark: 965
```

**Comment by fasheng** [comment] 2020-03-01 02:35
Well, the Fever API limit a maximum of 50, and miniflux follow the rule. I will add variable document for it later.
https://feedafever.com/api
https://github.com/miniflux/miniflux/blob/master/fever/handler.go#L245

Since elfedd-protocol fetch articles id by id, if you could not receive news, just run `elfeed-protocol-fever-reinit`.

And I use a timer to fetch articles automatically, hope helps :)
```elisp
(run-at-time 300 300
             (lambda () (when (= elfeed-curl-queue-active 0)
                          (elfeed-update))))
```

**Comment by vxid** [comment] 2020-03-01 16:05
Thanks a lot for your answer. I'll try to see if I can do anything on the Miniflux side by directly deleting read files.

**Comment by fasheng** [comment] 2020-03-02 10:55
I tested `miniflux:2.0.20`'s Fever API today, and reproduced the issue you said. Looks miniflux could not dispatch the `with_ids` argument correctly and always report the first 50 articles.

Here is my test command:
```sh
curl -XPOST -d 'api_key=xxx&with_ids=50,51' 'https://localhost/fever/?api&items' | jq .
```

And you could test API with the following HTML page, too:
https://feedafever.com/gateway/public/api-widget.html.zip

**Comment by fasheng** [comment] 2020-03-02 11:37
If send `with_ids` as the URL parameter it will works:
```
curl -XPOST -d 'api_key=xxx' 'https://localhost/fever/?api&items&with_ids=50,51' | jq .
```
I will test if the workaround works for TTRSS's Fever API later.

**Comment by vxid** [comment] 2020-03-02 12:18
@fasheng I did not understand you in your previous post, I thought you said that fetching the first 50 articles was expected behavior.

I somewhat mitigated the issue by setting a very low threshold for article deletion within miniflux using the `CLEANUP_FREQUENCY_HOURS` and `CLEANUP_ARCHIVE_READ_DAYS` variables but correcting the issue from within elfeed-protocol would of course be better.

Thanks for taking the time to do this!

**Comment by fasheng** [comment] 2020-03-02 14:12
I misunderstand you before. Anyway, 0.7.4 will works for both ttrss and miniflux's fever API now. Enjoy!

**Comment by fasheng** [comment] 2020-03-04 02:43
Looks miniflux really lightweight and powerful,  it support wallabag by default, which is helpful for me. I set `CLEANUP_ARCHIVE_READ_DAYS` to a big value to avoid elfeed-protocol couldn't fetch articles continuously if not running for a long time. Runs well after two days of testing, any problem please report to me, I just close the issue now~

**Closed by fasheng** 2020-03-04 02:43 UTC

**Comment by vxid** [comment] 2020-03-05 15:45
I can confirm that it fully works now. Thanks a lot for your efforts, @fasheng
